spring.application.name=shareplate

server.port=8080

# DATABASE
spring.datasource.url=${SHAREPLATE_DB_URL:jdbc:postgresql://localhost:5432/shareplate}
spring.datasource.username=${SHAREPLATE_DB_USERNAME}
spring.datasource.password=${SHAREPLATE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
shareplate.jwt.secret=${SHAREPLATE_JWT_SECRET}
shareplate.jwt.expiration-ms=86400000

# EMAIL
spring.mail.host=${SHAREPLATE_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SHAREPLATE_MAIL_PORT:587}
spring.mail.username=${SHAREPLATE_MAIL_USERNAME}
spring.mail.password=${SHAREPLATE_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

shareplate.mail.from=${SHAREPLATE_MAIL_FROM:${SHAREPLATE_MAIL_USERNAME}}

# FRONTEND
shareplate.frontend-url=${SHAREPLATE_FRONTEND_URL:http://localhost:5173}